version: "3"
services:
  vanilla:
    build:
      context: .
      dockerfile: vanilla.dockerfile
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
    volumes:
      - ~/.aws:/root/.aws
      - ./:/root/pipper
      - ~/.pipper:/root/.pipper
